version: "2"
services:
  mongodb:
    image: mongo
    container_name: mongodb
  #  volumes: uncomment for persistent data
      #- ./data/:/data/db
  cat_app_js:
    build: ./js_app
    container_name: catAppJS
    depends_on:
        - mongodb
    links:
        - mongodb
  cat_app_python:
    build: ./python_app
    container_name: catAppPython
    depends_on:
        - mongodb
    links:
        - mongodb
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
        - cat_app_js
        - cat_app_python
    links:
        - cat_app_js
        - cat_app_python
    ports:
      - "443:443"
    environment:
      - HTUSER=admin
      - HTPASSWD=admin 
